version: 0.2


phases:
   install:
    commands:
      - apt update
      - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
      - dpkg -i packages-microsoft-prod.deb
      - add-apt-repository universe
      - apt install -y apt-transport-https
      - apt update
      - apt install -y dotnet-sdk-5.0
   build:
    commands:
      - echo Build started on `date`
      - ls
      - cd ASP.NET-MVC/
      - cd BookShop/
      - dotnet build
      - dotnet test